In [2]:
!pip install pandas lightgbm optuna scikit-learn

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 380.1/380.1 kB 4.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 233.4/233.4 kB 13.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.8/78.8 kB 12.0 MB/s eta 0:00:00


In [3]:
!pip install xgboost

In [4]:
import pandas as pd
from lightgbm import LGBMRanker
from xgboost import XGBRanker
from sklearn.model_selection import train_test_split
from sklearn.metrics import ndcg_score
import optuna
import numpy as np

In [5]:
df = pd.read_csv('intern_task.csv')
print(df.info())
print(df.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 235258 entries, 0 to 235257
Columns: 146 entries, rank to feature_143
dtypes: float64(140), int64(6)
memory usage: 262.1 MB
None
                rank       query_id      feature_0      feature_1  \
count  235258.000000  235258.000000  235258.000000  235258.000000   
mean        0.677869   14828.413401       1.911960       0.206233   
std         0.830033    8193.945170       1.237374       0.579089   
min         0.000000      10.000000       0.000000       0.000000   
25%         0.000000    8215.000000       1.000000       0.000000   
50%         0.000000   14935.000000       2.000000       0.000000   
75%         1.000000   21580.000000       3.000000       0.000000   
max         4.000000   29995.000000      31.000000      18.000000   

           feature_2      feature_3      feature_4      feature_5  \
count  235258.000000  235258.000000  235258.000000  235258.000000   
mean        1.189847       0.550272       1.960082       0.80

In [6]:
X = df.drop(['rank'], axis=1)
y = df['rank']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [7]:
def ndcg_at_k(y_true, y_score, query_ids, k=5):
    def dcg_at_k(r, k):
        r = np.asfarray(r)[:k]
        if r.size:
            return np.sum((2 ** r - 1) / np.log2(np.arange(2, r.size + 2)))
        return 0.

    def ndcg_at_k(r, k):
        idcg = dcg_at_k(sorted(r, reverse=True), k)
        if not idcg:
            return 0.
        return dcg_at_k(r, k) / idcg

    ndcg_scores = []
    unique_queries = np.unique(query_ids)

    for query in unique_queries:
        query_indices = np.where(query_ids == query)[0]
        y_true_query = y_true[query_indices]
        y_score_query = y_score[query_indices]

        order = np.argsort(y_score_query)[::-1]
        y_true_query_sorted = y_true_query[order]

        ndcg_scores.append(ndcg_at_k(y_true_query_sorted, k))

    return np.mean(ndcg_scores)

In [ ]:
def objective_lgbm(trial):
    num_leaves = trial.suggest_int('num_leaves', 10, 100)
    max_depth = trial.suggest_int('max_depth', 3, 10)
    learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3)
    num_boost_round = trial.suggest_int('num_boost_round', 50, 500)
    min_child_samples = trial.suggest_int('min_child_samples', 5, 50)
    reg_alpha = trial.suggest_float('reg_alpha', 0.0, 1.0)
    reg_lambda = trial.suggest_float('reg_lambda', 0.0, 1.0)

    model = LGBMRanker(objective='lambdarank',
                       metric='ndcg',
                       num_leaves=num_leaves,
                       max_depth=max_depth,
                       learning_rate=learning_rate,
                       n_estimators=num_boost_round,
                       min_child_samples=min_child_samples,
                       reg_alpha=reg_alpha,
                       reg_lambda=reg_lambda,
                       random_state=42
                       )

    model.fit(X_train, y_train, group=X_train.groupby('query_id').size().values)
    y_pred = model.predict(X_test)
    query_ids = X_test['query_id'].values
    ndcg_5 = ndcg_at_k(y_test.values, y_pred, query_ids, k=5)
    return ndcg_5

Обучим сначлаа LGBMRanker, XGBRanker на ненормализованных данных, посмотрим, что они скажут

In [ ]:
study_lgbm = optuna.create_study(direction='maximize')
study_lgbm.optimize(objective_lgbm, n_trials=50)

[I 2024-04-27 14:21:54,701] A new study created in memory with name: no-name-1067ae76-3843-45b4-8a36-0651967af0e2


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.368635 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 26698
[LightGBM] [Info] Number of data points in the train set: 188206, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further s

[I 2024-04-27 14:22:52,079] Trial 0 finished with value: 0.5167747782588693 and parameters: {'num_leaves': 15, 'max_depth': 4, 'learning_rate': 0.18525619726611026, 'num_boost_round': 311, 'min_child_samples': 27, 'reg_alpha': 0.9448999441121265, 'reg_lambda': 0.5175316641534804}. Best is trial 0 with value: 0.5167747782588693.


[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.148356 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 26698
[LightGBM] [Info] Number of data points in the train set: 188206, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with 

[I 2024-04-27 14:24:38,792] Trial 1 finished with value: 0.5306737911337334 and parameters: {'num_leaves': 63, 'max_depth': 7, 'learning_rate': 0.2624605627029138, 'num_boost_round': 485, 'min_child_samples': 23, 'reg_alpha': 0.23903936646682444, 'reg_lambda': 0.31185185877510113}. Best is trial 1 with value: 0.5306737911337334.


[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.150490 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 26698
[LightGBM] [Info] Number of data points in the train set: 188206, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with 

[I 2024-04-27 14:25:13,813] Trial 2 finished with value: 0.5144857166275908 and parameters: {'num_leaves': 95, 'max_depth': 4, 'learning_rate': 0.2797445985280577, 'num_boost_round': 186, 'min_child_samples': 18, 'reg_alpha': 0.13164929853093232, 'reg_lambda': 0.7134797493003907}. Best is trial 1 with value: 0.5306737911337334.


[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.156919 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 26698
[LightGBM] [Info] Number of data points in the train set: 188206, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with 

[I 2024-04-27 14:25:41,178] Trial 3 finished with value: 0.514766572874536 and parameters: {'num_leaves': 81, 'max_depth': 6, 'learning_rate': 0.22839853739080973, 'num_boost_round': 104, 'min_child_samples': 16, 'reg_alpha': 0.7170339036166512, 'reg_lambda': 0.1404293845060135}. Best is trial 1 with value: 0.5306737911337334.


[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.151000 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 26698
[LightGBM] [Info] Number of data points in the train set: 188206, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf


[I 2024-04-27 14:26:00,211] Trial 4 finished with value: 0.48943364790915656 and parameters: {'num_leaves': 44, 'max_depth': 4, 'learning_rate': 0.05644849904033165, 'num_boost_round': 86, 'min_child_samples': 16, 'reg_alpha': 0.0024874900764113583, 'reg_lambda': 0.20840907311396684}. Best is trial 1 with value: 0.5306737911337334.


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.749067 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 26698
[LightGBM] [Info] Number of data points in the train set: 188206, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf


[I 2024-04-27 14:26:44,062] Trial 5 finished with value: 0.5123742026879751 and parameters: {'num_leaves': 21, 'max_depth': 5, 'learning_rate': 0.09375423949136762, 'num_boost_round': 221, 'min_child_samples': 10, 'reg_alpha': 0.03943966824769929, 'reg_lambda': 0.025548543717547778}. Best is trial 1 with value: 0.5306737911337334.


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.373711 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 26698
[LightGBM] [Info] Number of data points in the train set: 188206, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further s

[I 2024-04-27 14:27:47,338] Trial 6 finished with value: 0.518477651936094 and parameters: {'num_leaves': 93, 'max_depth': 4, 'learning_rate': 0.22926758576163672, 'num_boost_round': 337, 'min_child_samples': 39, 'reg_alpha': 0.9381214522152127, 'reg_lambda': 0.9276547761499946}. Best is trial 1 with value: 0.5306737911337334.


[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.167129 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 26698
[LightGBM] [Info] Number of data points in the train set: 188206, number of used features: 141


[I 2024-04-27 14:29:01,743] Trial 7 finished with value: 0.5168997116550276 and parameters: {'num_leaves': 54, 'max_depth': 10, 'learning_rate': 0.024602594137147105, 'num_boost_round': 290, 'min_child_samples': 27, 'reg_alpha': 0.6961694347933566, 'reg_lambda': 0.6830178447144423}. Best is trial 1 with value: 0.5306737911337334.


[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.163721 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 26698
[LightGBM] [Info] Number of data points in the train set: 188206, number of used features: 141


[I 2024-04-27 14:29:18,684] Trial 8 finished with value: 0.5091124807943992 and parameters: {'num_leaves': 24, 'max_depth': 9, 'learning_rate': 0.2587057139240526, 'num_boost_round': 61, 'min_child_samples': 8, 'reg_alpha': 0.5333438394643573, 'reg_lambda': 0.17195702336158802}. Best is trial 1 with value: 0.5306737911337334.


[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.251505 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 26698
[LightGBM] [Info] Number of data points in the train set: 188206, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with 

[I 2024-04-27 14:30:48,035] Trial 9 finished with value: 0.5143609281599909 and parameters: {'num_leaves': 96, 'max_depth': 5, 'learning_rate': 0.04181891189473895, 'num_boost_round': 488, 'min_child_samples': 16, 'reg_alpha': 0.22229277291745075, 'reg_lambda': 0.18951174373694624}. Best is trial 1 with value: 0.5306737911337334.


[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.158266 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 26698
[LightGBM] [Info] Number of data points in the train set: 188206, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with 

[I 2024-04-27 14:32:38,231] Trial 10 finished with value: 0.5337261031188291 and parameters: {'num_leaves': 70, 'max_depth': 8, 'learning_rate': 0.13787273789893043, 'num_boost_round': 497, 'min_child_samples': 44, 'reg_alpha': 0.3525343223631716, 'reg_lambda': 0.4143194483896433}. Best is trial 10 with value: 0.5337261031188291.


[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.222578 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 26698
[LightGBM] [Info] Number of data points in the train set: 188206, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with 

[I 2024-04-27 14:34:30,791] Trial 11 finished with value: 0.5327989798023459 and parameters: {'num_leaves': 71, 'max_depth': 8, 'learning_rate': 0.157008940036668, 'num_boost_round': 499, 'min_child_samples': 50, 'reg_alpha': 0.3436361872459024, 'reg_lambda': 0.4276610321423939}. Best is trial 10 with value: 0.5337261031188291.


[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.283234 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 26698
[LightGBM] [Info] Number of data points in the train set: 188206, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with 

[I 2024-04-27 14:36:03,261] Trial 12 finished with value: 0.534172535257233 and parameters: {'num_leaves': 72, 'max_depth': 8, 'learning_rate': 0.12393731776331518, 'num_boost_round': 399, 'min_child_samples': 49, 'reg_alpha': 0.3991657421500957, 'reg_lambda': 0.4229337466320277}. Best is trial 12 with value: 0.534172535257233.


[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.152121 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 26698
[LightGBM] [Info] Number of data points in the train set: 188206, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with 

[I 2024-04-27 14:37:33,991] Trial 13 finished with value: 0.5327398329401439 and parameters: {'num_leaves': 76, 'max_depth': 8, 'learning_rate': 0.11181460278432809, 'num_boost_round': 392, 'min_child_samples': 49, 'reg_alpha': 0.46101648676931906, 'reg_lambda': 0.5001351480202343}. Best is trial 12 with value: 0.534172535257233.


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.570333 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 26698
[LightGBM] [Info] Number of data points in the train set: 188206, number of used features: 141


[I 2024-04-27 14:39:09,184] Trial 14 finished with value: 0.5306137802587932 and parameters: {'num_leaves': 44, 'max_depth': 10, 'learning_rate': 0.1174941809892838, 'num_boost_round': 408, 'min_child_samples': 37, 'reg_alpha': 0.44301348867106727, 'reg_lambda': 0.6469943092520045}. Best is trial 12 with value: 0.534172535257233.


[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.150136 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 26698
[LightGBM] [Info] Number of data points in the train set: 188206, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf


[I 2024-04-27 14:40:41,435] Trial 15 finished with value: 0.5296321518230205 and parameters: {'num_leaves': 58, 'max_depth': 8, 'learning_rate': 0.15997542135793555, 'num_boost_round': 421, 'min_child_samples': 39, 'reg_alpha': 0.6044286671782562, 'reg_lambda': 0.37740646371126585}. Best is trial 12 with value: 0.534172535257233.


[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.153731 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 26698
[LightGBM] [Info] Number of data points in the train set: 188206, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with 

[I 2024-04-27 14:42:03,458] Trial 16 finished with value: 0.533773546362638 and parameters: {'num_leaves': 84, 'max_depth': 7, 'learning_rate': 0.07561342136792858, 'num_boost_round': 364, 'min_child_samples': 44, 'reg_alpha': 0.33942936885256575, 'reg_lambda': 0.575897259473976}. Best is trial 12 with value: 0.534172535257233.


[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.237750 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 26698
[LightGBM] [Info] Number of data points in the train set: 188206, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with 

[I 2024-04-27 14:43:17,075] Trial 17 finished with value: 0.5229142408610631 and parameters: {'num_leaves': 82, 'max_depth': 6, 'learning_rate': 0.07967493900611924, 'num_boost_round': 358, 'min_child_samples': 34, 'reg_alpha': 0.33590195100296366, 'reg_lambda': 0.8147630818399645}. Best is trial 12 with value: 0.534172535257233.


[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.166358 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 26698
[LightGBM] [Info] Number of data points in the train set: 188206, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with 

[I 2024-04-27 14:44:19,595] Trial 18 finished with value: 0.5022026820843677 and parameters: {'num_leaves': 85, 'max_depth': 7, 'learning_rate': 0.010345388734735034, 'num_boost_round': 255, 'min_child_samples': 45, 'reg_alpha': 0.21591130358484528, 'reg_lambda': 0.5861103898112371}. Best is trial 12 with value: 0.534172535257233.


[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.154682 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 26698
[LightGBM] [Info] Number of data points in the train set: 188206, number of used features: 141


[I 2024-04-27 14:45:53,656] Trial 19 finished with value: 0.5333615357404287 and parameters: {'num_leaves': 46, 'max_depth': 9, 'learning_rate': 0.06586254250458963, 'num_boost_round': 432, 'min_child_samples': 33, 'reg_alpha': 0.7861127443419946, 'reg_lambda': 0.8024708575735802}. Best is trial 12 with value: 0.534172535257233.


[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.147631 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 26698
[LightGBM] [Info] Number of data points in the train set: 188206, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with 

[I 2024-04-27 14:47:16,406] Trial 20 finished with value: 0.5306698233462388 and parameters: {'num_leaves': 66, 'max_depth': 7, 'learning_rate': 0.17789611149662282, 'num_boost_round': 360, 'min_child_samples': 43, 'reg_alpha': 0.5718273748732823, 'reg_lambda': 0.3029602806541567}. Best is trial 12 with value: 0.534172535257233.


[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.257747 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 26698
[LightGBM] [Info] Number of data points in the train set: 188206, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf


[I 2024-04-27 14:48:58,422] Trial 21 finished with value: 0.5308290027422365 and parameters: {'num_leaves': 74, 'max_depth': 9, 'learning_rate': 0.12480793634351721, 'num_boost_round': 446, 'min_child_samples': 45, 'reg_alpha': 0.36813156263576746, 'reg_lambda': 0.4206634087983951}. Best is trial 12 with value: 0.534172535257233.


[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.154577 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 26698
[LightGBM] [Info] Number of data points in the train set: 188206, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with 

[I 2024-04-27 14:50:48,922] Trial 22 finished with value: 0.5345733740121563 and parameters: {'num_leaves': 87, 'max_depth': 8, 'learning_rate': 0.1455961484033929, 'num_boost_round': 465, 'min_child_samples': 42, 'reg_alpha': 0.39104046975607915, 'reg_lambda': 0.55381869713576}. Best is trial 22 with value: 0.5345733740121563.


[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.263099 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 26698
[LightGBM] [Info] Number of data points in the train set: 188206, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with 

[I 2024-04-27 14:52:05,168] Trial 23 finished with value: 0.5262610887144038 and parameters: {'num_leaves': 88, 'max_depth': 6, 'learning_rate': 0.08632467993269019, 'num_boost_round': 379, 'min_child_samples': 50, 'reg_alpha': 0.4286725613694803, 'reg_lambda': 0.5818618691691774}. Best is trial 22 with value: 0.5345733740121563.


[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.153644 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 26698
[LightGBM] [Info] Number of data points in the train set: 188206, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with 

[I 2024-04-27 14:53:47,102] Trial 24 finished with value: 0.5317750358983914 and parameters: {'num_leaves': 99, 'max_depth': 7, 'learning_rate': 0.19573268840187913, 'num_boost_round': 449, 'min_child_samples': 41, 'reg_alpha': 0.2781944399548723, 'reg_lambda': 0.5285631431698576}. Best is trial 22 with value: 0.5345733740121563.


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.393055 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 26698
[LightGBM] [Info] Number of data points in the train set: 188206, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further s

[I 2024-04-27 14:55:19,682] Trial 25 finished with value: 0.5373661001696393 and parameters: {'num_leaves': 87, 'max_depth': 9, 'learning_rate': 0.10264292610732471, 'num_boost_round': 336, 'min_child_samples': 35, 'reg_alpha': 0.14067762968187958, 'reg_lambda': 0.7409153013004788}. Best is trial 25 with value: 0.5373661001696393.


[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.154918 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 26698
[LightGBM] [Info] Number of data points in the train set: 188206, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with 

[I 2024-04-27 14:56:36,160] Trial 26 finished with value: 0.5341721073745997 and parameters: {'num_leaves': 90, 'max_depth': 9, 'learning_rate': 0.14594042805346236, 'num_boost_round': 324, 'min_child_samples': 33, 'reg_alpha': 0.09700903414742829, 'reg_lambda': 0.7687296232579496}. Best is trial 25 with value: 0.5373661001696393.


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.387873 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 26698
[LightGBM] [Info] Number of data points in the train set: 188206, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf


[I 2024-04-27 14:57:53,114] Trial 27 finished with value: 0.532427381945944 and parameters: {'num_leaves': 77, 'max_depth': 10, 'learning_rate': 0.10305344061754035, 'num_boost_round': 265, 'min_child_samples': 35, 'reg_alpha': 0.13500157105155258, 'reg_lambda': 0.9000171509224585}. Best is trial 25 with value: 0.5373661001696393.


[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.146548 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 26698
[LightGBM] [Info] Number of data points in the train set: 188206, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf


[I 2024-04-27 14:59:35,664] Trial 28 finished with value: 0.5347022441701026 and parameters: {'num_leaves': 60, 'max_depth': 8, 'learning_rate': 0.213826065284343, 'num_boost_round': 460, 'min_child_samples': 30, 'reg_alpha': 0.6239054789056753, 'reg_lambda': 0.6456400525822409}. Best is trial 25 with value: 0.5373661001696393.


[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.148297 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 26698
[LightGBM] [Info] Number of data points in the train set: 188206, number of used features: 141


[I 2024-04-27 15:00:10,849] Trial 29 finished with value: 0.5232927870560484 and parameters: {'num_leaves': 32, 'max_depth': 9, 'learning_rate': 0.201278788478989, 'num_boost_round': 161, 'min_child_samples': 30, 'reg_alpha': 0.8449088955098363, 'reg_lambda': 0.994000029054928}. Best is trial 25 with value: 0.5373661001696393.


[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.145837 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 26698
[LightGBM] [Info] Number of data points in the train set: 188206, number of used features: 141


[I 2024-04-27 15:01:46,527] Trial 30 finished with value: 0.5293943940646952 and parameters: {'num_leaves': 52, 'max_depth': 10, 'learning_rate': 0.22014722299622758, 'num_boost_round': 460, 'min_child_samples': 22, 'reg_alpha': 0.6257513887088164, 'reg_lambda': 0.7574319388508821}. Best is trial 25 with value: 0.5373661001696393.


[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.172330 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 26698
[LightGBM] [Info] Number of data points in the train set: 188206, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with 

[I 2024-04-27 15:03:14,374] Trial 31 finished with value: 0.5359383122247956 and parameters: {'num_leaves': 62, 'max_depth': 8, 'learning_rate': 0.17462256172109916, 'num_boost_round': 412, 'min_child_samples': 48, 'reg_alpha': 0.4955792018072316, 'reg_lambda': 0.6407256170051105}. Best is trial 25 with value: 0.5373661001696393.


[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.149454 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 26698
[LightGBM] [Info] Number of data points in the train set: 188206, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf


[I 2024-04-27 15:04:55,961] Trial 32 finished with value: 0.530132697315989 and parameters: {'num_leaves': 63, 'max_depth': 8, 'learning_rate': 0.17555433996464256, 'num_boost_round': 466, 'min_child_samples': 24, 'reg_alpha': 0.5266408514037327, 'reg_lambda': 0.6689939416056304}. Best is trial 25 with value: 0.5373661001696393.


[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.151893 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 26698
[LightGBM] [Info] Number of data points in the train set: 188206, number of used features: 141


[I 2024-04-27 15:06:06,026] Trial 33 finished with value: 0.520023655116069 and parameters: {'num_leaves': 10, 'max_depth': 9, 'learning_rate': 0.2094258251054778, 'num_boost_round': 420, 'min_child_samples': 29, 'reg_alpha': 0.6620335065405027, 'reg_lambda': 0.6397882211953372}. Best is trial 25 with value: 0.5373661001696393.


[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.153110 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 26698
[LightGBM] [Info] Number of data points in the train set: 188206, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with 

[I 2024-04-27 15:06:54,280] Trial 34 finished with value: 0.5049720853549792 and parameters: {'num_leaves': 60, 'max_depth': 3, 'learning_rate': 0.297260557448836, 'num_boost_round': 301, 'min_child_samples': 37, 'reg_alpha': 0.4981892808791744, 'reg_lambda': 0.8621073836989822}. Best is trial 25 with value: 0.5373661001696393.


[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.159180 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 26698
[LightGBM] [Info] Number of data points in the train set: 188206, number of used features: 141


[I 2024-04-27 15:08:24,482] Trial 35 finished with value: 0.5264451182668051 and parameters: {'num_leaves': 35, 'max_depth': 8, 'learning_rate': 0.2370556072894304, 'num_boost_round': 461, 'min_child_samples': 31, 'reg_alpha': 0.7714913647007999, 'reg_lambda': 0.7208561083478263}. Best is trial 25 with value: 0.5373661001696393.


[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.149438 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 26698
[LightGBM] [Info] Number of data points in the train set: 188206, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with 

[I 2024-04-27 15:09:34,638] Trial 36 finished with value: 0.5247150357957606 and parameters: {'num_leaves': 50, 'max_depth': 7, 'learning_rate': 0.16752692476214393, 'num_boost_round': 338, 'min_child_samples': 41, 'reg_alpha': 0.2709924980098411, 'reg_lambda': 0.6037172958740915}. Best is trial 25 with value: 0.5373661001696393.


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.391998 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 26698
[LightGBM] [Info] Number of data points in the train set: 188206, number of used features: 141


[I 2024-04-27 15:11:12,235] Trial 37 finished with value: 0.534192131698621 and parameters: {'num_leaves': 66, 'max_depth': 9, 'learning_rate': 0.1909468651455538, 'num_boost_round': 387, 'min_child_samples': 25, 'reg_alpha': 0.5651888645706263, 'reg_lambda': 0.5335908103166288}. Best is trial 25 with value: 0.5373661001696393.


[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.151636 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 26698
[LightGBM] [Info] Number of data points in the train set: 188206, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf


[I 2024-04-27 15:12:40,680] Trial 38 finished with value: 0.5321502566794759 and parameters: {'num_leaves': 40, 'max_depth': 8, 'learning_rate': 0.13564388087199455, 'num_boost_round': 475, 'min_child_samples': 47, 'reg_alpha': 0.18333803303388452, 'reg_lambda': 0.7134618005069302}. Best is trial 25 with value: 0.5373661001696393.


[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.155621 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 26698
[LightGBM] [Info] Number of data points in the train set: 188206, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with 

[I 2024-04-27 15:14:15,383] Trial 39 finished with value: 0.5229750229442135 and parameters: {'num_leaves': 91, 'max_depth': 6, 'learning_rate': 0.2518929847546109, 'num_boost_round': 436, 'min_child_samples': 37, 'reg_alpha': 0.47957055978278734, 'reg_lambda': 0.48640246950401533}. Best is trial 25 with value: 0.5373661001696393.


[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.147033 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 26698
[LightGBM] [Info] Number of data points in the train set: 188206, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with 

[I 2024-04-27 15:15:03,485] Trial 40 finished with value: 0.5247736869293589 and parameters: {'num_leaves': 79, 'max_depth': 7, 'learning_rate': 0.10210788282323573, 'num_boost_round': 217, 'min_child_samples': 41, 'reg_alpha': 0.0218184061352132, 'reg_lambda': 0.2939307928483046}. Best is trial 25 with value: 0.5373661001696393.


[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.155942 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 26698
[LightGBM] [Info] Number of data points in the train set: 188206, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf


[I 2024-04-27 15:16:33,043] Trial 41 finished with value: 0.5288355443152544 and parameters: {'num_leaves': 67, 'max_depth': 9, 'learning_rate': 0.1910740453127675, 'num_boost_round': 380, 'min_child_samples': 21, 'reg_alpha': 0.580577909584085, 'reg_lambda': 0.5249448098850223}. Best is trial 25 with value: 0.5373661001696393.


[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.145576 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 26698
[LightGBM] [Info] Number of data points in the train set: 188206, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf


[I 2024-04-27 15:18:19,120] Trial 42 finished with value: 0.5364908143519254 and parameters: {'num_leaves': 100, 'max_depth': 9, 'learning_rate': 0.21319203757693497, 'num_boost_round': 407, 'min_child_samples': 26, 'reg_alpha': 0.6895704974883765, 'reg_lambda': 0.6318152778289713}. Best is trial 25 with value: 0.5373661001696393.


[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.151336 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 26698
[LightGBM] [Info] Number of data points in the train set: 188206, number of used features: 141


[I 2024-04-27 15:20:08,657] Trial 43 finished with value: 0.5321378607015974 and parameters: {'num_leaves': 99, 'max_depth': 10, 'learning_rate': 0.22384358024777828, 'num_boost_round': 419, 'min_child_samples': 27, 'reg_alpha': 0.7249314933916303, 'reg_lambda': 0.7026470317344911}. Best is trial 25 with value: 0.5373661001696393.


[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.217694 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 26698
[LightGBM] [Info] Number of data points in the train set: 188206, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with 

[I 2024-04-27 15:21:39,851] Trial 44 finished with value: 0.531158686022964 and parameters: {'num_leaves': 94, 'max_depth': 8, 'learning_rate': 0.24382951930582666, 'num_boost_round': 341, 'min_child_samples': 19, 'reg_alpha': 0.8843265455552309, 'reg_lambda': 0.6249914905305328}. Best is trial 25 with value: 0.5373661001696393.


[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.152352 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 26698
[LightGBM] [Info] Number of data points in the train set: 188206, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf


[I 2024-04-27 15:23:45,628] Trial 45 finished with value: 0.5290516951885137 and parameters: {'num_leaves': 86, 'max_depth': 9, 'learning_rate': 0.26976960472865963, 'num_boost_round': 483, 'min_child_samples': 11, 'reg_alpha': 0.6361297630170718, 'reg_lambda': 0.7625247560766995}. Best is trial 25 with value: 0.5373661001696393.


[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.157188 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 26698
[LightGBM] [Info] Number of data points in the train set: 188206, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with 

[I 2024-04-27 15:25:33,366] Trial 46 finished with value: 0.5313131854396766 and parameters: {'num_leaves': 100, 'max_depth': 8, 'learning_rate': 0.2162914295964594, 'num_boost_round': 404, 'min_child_samples': 31, 'reg_alpha': 0.9949228159641315, 'reg_lambda': 0.02264442132284883}. Best is trial 25 with value: 0.5373661001696393.


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.404330 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 26698
[LightGBM] [Info] Number of data points in the train set: 188206, number of used features: 141


[I 2024-04-27 15:26:55,616] Trial 47 finished with value: 0.5272392515009529 and parameters: {'num_leaves': 57, 'max_depth': 10, 'learning_rate': 0.20513962071492475, 'num_boost_round': 315, 'min_child_samples': 47, 'reg_alpha': 0.6816134705138497, 'reg_lambda': 0.4727005183227181}. Best is trial 25 with value: 0.5373661001696393.


[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.158483 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 26698
[LightGBM] [Info] Number of data points in the train set: 188206, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf


[I 2024-04-27 15:28:53,260] Trial 48 finished with value: 0.5354594584245931 and parameters: {'num_leaves': 95, 'max_depth': 9, 'learning_rate': 0.1786159953122448, 'num_boost_round': 442, 'min_child_samples': 26, 'reg_alpha': 0.7332048882134844, 'reg_lambda': 0.6649684767752829}. Best is trial 25 with value: 0.5373661001696393.


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.409428 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 26698
[LightGBM] [Info] Number of data points in the train set: 188206, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf


[I 2024-04-27 15:30:22,992] Trial 49 finished with value: 0.5302793613556971 and parameters: {'num_leaves': 95, 'max_depth': 9, 'learning_rate': 0.17864234520098377, 'num_boost_round': 284, 'min_child_samples': 28, 'reg_alpha': 0.740738135171739, 'reg_lambda': 0.8409025683743185}. Best is trial 25 with value: 0.5373661001696393.


In [ ]:
print(f'Best NDCG@5 for LGBM: {study_lgbm.best_value:.4f}')
print('Best hyperparameters for LGBM:')
print(study_lgbm.best_params)

Best NDCG@5 for LGBM: 0.5374
Best hyperparameters for LGBM:
{'num_leaves': 87, 'max_depth': 9, 'learning_rate': 0.10264292610732471, 'num_boost_round': 336, 'min_child_samples': 35, 'reg_alpha': 0.14067762968187958, 'reg_lambda': 0.7409153013004788}


Best NDCG@5 for LGBM: 0.5374
Best hyperparameters for LGBM:
{'num_leaves': 87, 'max_depth': 9, 'learning_rate': 0.10264292610732471, 'num_boost_round': 336, 'min_child_samples': 35, 'reg_alpha': 0.14067762968187958, 'reg_lambda': 0.7409153013004788}

In [8]:
def objective_xgb(trial):
    params = {
        'objective': 'rank:ndcg',
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3),
        'max_depth': trial.suggest_int('max_depth', 3, 10),
        'n_estimators': trial.suggest_int('n_estimators', 50, 500),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'gamma': trial.suggest_float('gamma', 0.0, 1.0),
        'subsample': trial.suggest_float('subsample', 0.5, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 1.0),
        'reg_alpha': trial.suggest_float('reg_alpha', 0.0, 1.0),
        'reg_lambda': trial.suggest_float('reg_lambda', 0.0, 1.0)
    }

    model = XGBRanker(**params)
    model.fit(X_train, y_train, group=X_train.groupby('query_id').size().values)

    y_pred = model.predict(X_test)
    query_ids = X_test['query_id'].values
    ndcg_5 = ndcg_at_k(y_test.values, y_pred, query_ids, k=5)
    return ndcg_5

In [9]:
study_xgb = optuna.create_study(direction='maximize')
study_xgb.optimize(objective_xgb, n_trials=50)

[I 2024-04-28 09:52:21,795] A new study created in memory with name: no-name-414bd940-2a38-42b8-9fb9-21057be1dbc3
[I 2024-04-28 09:54:02,750] Trial 0 finished with value: 0.5254054283688235 and parameters: {'learning_rate': 0.26218993026078813, 'max_depth': 10, 'n_estimators': 180, 'min_child_weight': 2, 'gamma': 0.08914924162477034, 'subsample': 0.5765190206098445, 'colsample_bytree': 0.8345556118632947, 'reg_alpha': 0.24865980102439433, 'reg_lambda': 0.4723289875435238}. Best is trial 0 with value: 0.5254054283688235.
[I 2024-04-28 09:54:57,253] Trial 1 finished with value: 0.5222489861015802 and parameters: {'learning_rate': 0.14686811331094282, 'max_depth': 9, 'n_estimators': 110, 'min_child_weight': 3, 'gamma': 0.17586310610448486, 'subsample': 0.9763738856040041, 'colsample_bytree': 0.9206445495342952, 'reg_alpha': 0.3680765008215475, 'reg_lambda': 0.937521181993417}. Best is trial 0 with value: 0.5254054283688235.
[I 2024-04-28 09:56:00,961] Trial 2 finished with value: 0.514947

In [10]:
print(f'Best NDCG@5 for XGB: {study_xgb.best_value:.4f}')
print('Best hyperparameters for XGB:')
print(study_xgb.best_params)

Best NDCG@5 for XGB: 0.5436
Best hyperparameters for XGB:
{'learning_rate': 0.18355585767238483, 'max_depth': 9, 'n_estimators': 456, 'min_child_weight': 2, 'gamma': 0.007183842663282607, 'subsample': 0.9619329921087644, 'colsample_bytree': 0.5487403237135628, 'reg_alpha': 0.46590326161117473, 'reg_lambda': 0.05390754790505921}


Best NDCG@5 for XGB: 0.5436
Best hyperparameters for XGB:
{'learning_rate': 0.18355585767238483, 'max_depth': 9, 'n_estimators': 456, 'min_child_weight': 2, 'gamma': 0.007183842663282607, 'subsample': 0.9619329921087644, 'colsample_bytree': 0.5487403237135628, 'reg_alpha': 0.46590326161117473, 'reg_lambda': 0.05390754790505921}


Теперь отнормализуем данные с помощью StandartScaler из sklearn`a и посмотрим, что получится!

In [11]:
from sklearn.preprocessing import StandardScaler

In [12]:
scaler = StandardScaler()
columns = list(X.columns)
columns.remove('query_id')
X_new = X.copy()
X_new[columns] = scaler.fit_transform(X_new[columns])

X_train_normalized, X_test_normalized, y_train_normalized, y_test_normalized = train_test_split(X_new, y, test_size=0.2, random_state=42)

In [13]:
pd.DataFrame(X_train_normalized).head()

query_id  feature_0  feature_1  feature_2  feature_3  feature_4  \
154012     19060  -0.737015   1.370720  -0.183032   0.568595  -0.797721   
169995     20845  -0.737015  -0.356135  -0.183032  -0.695715  -0.797721   
147302     18325  -0.737015  -0.356135  -0.183032   0.568595   0.033167   
187614     22585  -0.737015  -0.356135  -0.183032   0.568595  -0.797721   
140275     17650   0.071150  -0.356135   0.781073  -0.695715   0.033167   

        feature_5  feature_6  feature_7  feature_8  ...  feature_134  \
154012   0.576653   3.392204   1.092516   0.535736  ...    -0.024367   
169995   0.576653  -0.366710   1.092516   0.771081  ...    -0.023651   
147302  -0.894132  -0.366710  -0.098040   0.436933  ...    -0.024367   
187614   0.576653  -0.366710   1.092516   1.030515  ...    -0.024367   
140275   0.576653  -0.366710   1.092516   0.333463  ...    -0.024367   

        feature_135  feature_136  feature_137  feature_138  feature_139  \
154012    -0.003950     0.543102     0.734952    -0.171766     1.831865   
169995    -0.003944    -0.697956     0.734952    -0.141470    -0.718582   
147302    -0.003950     0.405205    -0.913423    -0.145082     0.556642   
187614    -0.003950     0.405205     0.734952    -0.104076     1.831865   
140275    -0.003950    -0.697956     0.621786     1.165303    -0.718582   

        feature_140  feature_141  feature_142  feature_143  
154012     1.331198    -0.128656    -0.022884     0.797334  
169995     3.091526    -0.128656    -0.069974     0.588236  
147302    -0.649485    -0.118120    -0.148457    -0.213306  
187614     0.162974    -0.128656    -0.305424    -0.457254  
140275     0.339403    -0.033825     0.008509     0.135190  

[5 rows x 145 columns]

In [11]:
def objective_lgbm_normalized(trial):
    num_leaves = trial.suggest_int('num_leaves', 10, 100)
    max_depth = trial.suggest_int('max_depth', 3, 10)
    learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3)
    num_boost_round = trial.suggest_int('num_boost_round', 50, 500)
    min_child_samples = trial.suggest_int('min_child_samples', 5, 50)
    reg_alpha = trial.suggest_float('reg_alpha', 0.0, 1.0)
    reg_lambda = trial.suggest_float('reg_lambda', 0.0, 1.0)

    model = LGBMRanker(objective='lambdarank',
                       metric='ndcg',
                       num_leaves=num_leaves,
                       max_depth=max_depth,
                       learning_rate=learning_rate,
                       n_estimators=num_boost_round,
                       min_child_samples=min_child_samples,
                       reg_alpha=reg_alpha,
                       reg_lambda=reg_lambda,
                       random_state=42
                       )

    model.fit(X_train_normalized, y_train_normalized, group=X_train_normalized.groupby('query_id').size().values)
    y_pred = model.predict(X_test_normalized)
    query_ids = X_test_normalized['query_id'].values
    ndcg_5 = ndcg_at_k(y_test_normalized.values, y_pred, query_ids, k=5)
    return ndcg_5

In [12]:
study_lgbm_normalized = optuna.create_study(direction='maximize')
study_lgbm_normalized.optimize(objective_lgbm_normalized, n_trials=50)

[I 2024-04-27 22:34:35,695] A new study created in memory with name: no-name-7746b2f9-84f1-45f0-9502-235060491ace


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.210827 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25872
[LightGBM] [Info] Number of data points in the train set: 58507, number of used features: 141


[I 2024-04-27 22:35:33,852] Trial 0 finished with value: 0.544856424582774 and parameters: {'num_leaves': 58, 'max_depth': 9, 'learning_rate': 0.01910694518090675, 'num_boost_round': 423, 'min_child_samples': 25, 'reg_alpha': 0.7193930934220838, 'reg_lambda': 0.7727070671761667}. Best is trial 0 with value: 0.544856424582774.


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.104960 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25872
[LightGBM] [Info] Number of data points in the train set: 58507, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf


[I 2024-04-27 22:36:13,899] Trial 1 finished with value: 0.5360465801991756 and parameters: {'num_leaves': 52, 'max_depth': 9, 'learning_rate': 0.18437705433451143, 'num_boost_round': 374, 'min_child_samples': 44, 'reg_alpha': 0.7308636934967967, 'reg_lambda': 0.25868612763739973}. Best is trial 0 with value: 0.544856424582774.


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.111508 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25872
[LightGBM] [Info] Number of data points in the train set: 58507, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further sp

[I 2024-04-27 22:36:23,764] Trial 2 finished with value: 0.5347746814460763 and parameters: {'num_leaves': 88, 'max_depth': 7, 'learning_rate': 0.23828675573405422, 'num_boost_round': 61, 'min_child_samples': 32, 'reg_alpha': 0.8312018815096228, 'reg_lambda': 0.45260816486521327}. Best is trial 0 with value: 0.544856424582774.


[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.106933 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25872
[LightGBM] [Info] Number of data points in the train set: 58507, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further sp

[I 2024-04-27 22:36:51,418] Trial 3 finished with value: 0.5284462851348015 and parameters: {'num_leaves': 80, 'max_depth': 3, 'learning_rate': 0.17874037438896773, 'num_boost_round': 474, 'min_child_samples': 6, 'reg_alpha': 0.9448534291022677, 'reg_lambda': 0.16091920941315274}. Best is trial 0 with value: 0.544856424582774.


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.108783 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25872
[LightGBM] [Info] Number of data points in the train set: 58507, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf


[I 2024-04-27 22:37:00,442] Trial 4 finished with value: 0.5333720994627938 and parameters: {'num_leaves': 79, 'max_depth': 9, 'learning_rate': 0.2764767572089457, 'num_boost_round': 52, 'min_child_samples': 50, 'reg_alpha': 0.6427916407857731, 'reg_lambda': 0.9314926148345735}. Best is trial 0 with value: 0.544856424582774.


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.107707 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25872
[LightGBM] [Info] Number of data points in the train set: 58507, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further sp

[I 2024-04-27 22:37:08,031] Trial 5 finished with value: 0.5221382882597468 and parameters: {'num_leaves': 27, 'max_depth': 4, 'learning_rate': 0.2529479360344707, 'num_boost_round': 98, 'min_child_samples': 29, 'reg_alpha': 0.9258377314844579, 'reg_lambda': 0.7902767797213527}. Best is trial 0 with value: 0.544856424582774.


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.114392 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25872
[LightGBM] [Info] Number of data points in the train set: 58507, number of used features: 141


[I 2024-04-27 22:37:22,199] Trial 6 finished with value: 0.5432154845485068 and parameters: {'num_leaves': 43, 'max_depth': 10, 'learning_rate': 0.19508473008326224, 'num_boost_round': 119, 'min_child_samples': 28, 'reg_alpha': 0.5386583986128002, 'reg_lambda': 0.3848520520076848}. Best is trial 0 with value: 0.544856424582774.


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.183987 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25872
[LightGBM] [Info] Number of data points in the train set: 58507, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further sp

[I 2024-04-27 22:37:45,045] Trial 7 finished with value: 0.5350809623258366 and parameters: {'num_leaves': 67, 'max_depth': 6, 'learning_rate': 0.27387991079088264, 'num_boost_round': 222, 'min_child_samples': 25, 'reg_alpha': 0.10935122773593653, 'reg_lambda': 0.2778627682177577}. Best is trial 0 with value: 0.544856424582774.


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.108340 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25872
[LightGBM] [Info] Number of data points in the train set: 58507, number of used features: 141


[I 2024-04-27 22:38:20,366] Trial 8 finished with value: 0.5296242675432652 and parameters: {'num_leaves': 21, 'max_depth': 6, 'learning_rate': 0.28067357584718183, 'num_boost_round': 453, 'min_child_samples': 29, 'reg_alpha': 0.844399984902439, 'reg_lambda': 0.3504627524946612}. Best is trial 0 with value: 0.544856424582774.


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.117191 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25872
[LightGBM] [Info] Number of data points in the train set: 58507, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf


[I 2024-04-27 22:38:28,941] Trial 9 finished with value: 0.5320412873387963 and parameters: {'num_leaves': 74, 'max_depth': 10, 'learning_rate': 0.24031721275803217, 'num_boost_round': 55, 'min_child_samples': 50, 'reg_alpha': 0.42598522772814285, 'reg_lambda': 0.9283467296403249}. Best is trial 0 with value: 0.544856424582774.


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.168896 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25872
[LightGBM] [Info] Number of data points in the train set: 58507, number of used features: 141


[I 2024-04-27 22:39:05,654] Trial 10 finished with value: 0.5375206797996288 and parameters: {'num_leaves': 38, 'max_depth': 8, 'learning_rate': 0.010592408156299301, 'num_boost_round': 327, 'min_child_samples': 16, 'reg_alpha': 0.2426820587006775, 'reg_lambda': 0.6713325174938212}. Best is trial 0 with value: 0.544856424582774.


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.113849 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25872
[LightGBM] [Info] Number of data points in the train set: 58507, number of used features: 141


[I 2024-04-27 22:39:29,747] Trial 11 finished with value: 0.5476272113226142 and parameters: {'num_leaves': 53, 'max_depth': 10, 'learning_rate': 0.048107587021159484, 'num_boost_round': 186, 'min_child_samples': 19, 'reg_alpha': 0.5389084462150311, 'reg_lambda': 0.6002423664712622}. Best is trial 11 with value: 0.5476272113226142.


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.112343 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25872
[LightGBM] [Info] Number of data points in the train set: 58507, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf


[I 2024-04-27 22:39:58,763] Trial 12 finished with value: 0.5465040407254933 and parameters: {'num_leaves': 100, 'max_depth': 8, 'learning_rate': 0.031028100698384135, 'num_boost_round': 198, 'min_child_samples': 17, 'reg_alpha': 0.4034644235284741, 'reg_lambda': 0.6461553296517024}. Best is trial 11 with value: 0.5476272113226142.


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.111993 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25872
[LightGBM] [Info] Number of data points in the train set: 58507, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further sp

[I 2024-04-27 22:40:23,970] Trial 13 finished with value: 0.5382569332985104 and parameters: {'num_leaves': 97, 'max_depth': 7, 'learning_rate': 0.08350796919337491, 'num_boost_round': 205, 'min_child_samples': 16, 'reg_alpha': 0.3646469193113366, 'reg_lambda': 0.5883304752347474}. Best is trial 11 with value: 0.5476272113226142.


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.101224 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25872
[LightGBM] [Info] Number of data points in the train set: 58507, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf


[I 2024-04-27 22:40:50,011] Trial 14 finished with value: 0.541271328688989 and parameters: {'num_leaves': 62, 'max_depth': 8, 'learning_rate': 0.0789952912615226, 'num_boost_round': 210, 'min_child_samples': 15, 'reg_alpha': 0.2775183397067571, 'reg_lambda': 0.5401110688350077}. Best is trial 11 with value: 0.5476272113226142.


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.104321 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25872
[LightGBM] [Info] Number of data points in the train set: 58507, number of used features: 141


[I 2024-04-27 22:41:11,130] Trial 15 finished with value: 0.5349360145008177 and parameters: {'num_leaves': 12, 'max_depth': 10, 'learning_rate': 0.07714044977042199, 'num_boost_round': 280, 'min_child_samples': 6, 'reg_alpha': 0.5502071302427944, 'reg_lambda': 0.6771904072901272}. Best is trial 11 with value: 0.5476272113226142.


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.101481 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25872
[LightGBM] [Info] Number of data points in the train set: 58507, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further sp

[I 2024-04-27 22:41:25,319] Trial 16 finished with value: 0.540145265198692 and parameters: {'num_leaves': 98, 'max_depth': 5, 'learning_rate': 0.11582575893272638, 'num_boost_round': 162, 'min_child_samples': 20, 'reg_alpha': 0.06437217432368092, 'reg_lambda': 0.7468038430779853}. Best is trial 11 with value: 0.5476272113226142.


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.099922 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25872
[LightGBM] [Info] Number of data points in the train set: 58507, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf


[I 2024-04-27 22:41:54,489] Trial 17 finished with value: 0.5485987749023586 and parameters: {'num_leaves': 43, 'max_depth': 8, 'learning_rate': 0.04480085403108468, 'num_boost_round': 278, 'min_child_samples': 36, 'reg_alpha': 0.4591439983864921, 'reg_lambda': 0.025661559346590535}. Best is trial 17 with value: 0.5485987749023586.


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.100606 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25872
[LightGBM] [Info] Number of data points in the train set: 58507, number of used features: 141


[I 2024-04-27 22:42:23,675] Trial 18 finished with value: 0.5381217005671778 and parameters: {'num_leaves': 45, 'max_depth': 9, 'learning_rate': 0.1304587483366598, 'num_boost_round': 290, 'min_child_samples': 37, 'reg_alpha': 0.6116109873147878, 'reg_lambda': 0.11307743859174943}. Best is trial 17 with value: 0.5485987749023586.


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.106336 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25872
[LightGBM] [Info] Number of data points in the train set: 58507, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf


[I 2024-04-27 22:42:54,331] Trial 19 finished with value: 0.5395028570070678 and parameters: {'num_leaves': 32, 'max_depth': 8, 'learning_rate': 0.050561507805432414, 'num_boost_round': 335, 'min_child_samples': 42, 'reg_alpha': 0.1965648814819857, 'reg_lambda': 0.07729152186752834}. Best is trial 17 with value: 0.5485987749023586.


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.194843 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25872
[LightGBM] [Info] Number of data points in the train set: 58507, number of used features: 141


[I 2024-04-27 22:43:24,260] Trial 20 finished with value: 0.5504056068686063 and parameters: {'num_leaves': 51, 'max_depth': 10, 'learning_rate': 0.11632666534661679, 'num_boost_round': 260, 'min_child_samples': 35, 'reg_alpha': 0.4542736385668392, 'reg_lambda': 0.018792752953076475}. Best is trial 20 with value: 0.5504056068686063.


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.103981 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25872
[LightGBM] [Info] Number of data points in the train set: 58507, number of used features: 141


[I 2024-04-27 22:43:52,480] Trial 21 finished with value: 0.5449559378142362 and parameters: {'num_leaves': 48, 'max_depth': 10, 'learning_rate': 0.11467740749183436, 'num_boost_round': 249, 'min_child_samples': 34, 'reg_alpha': 0.45972553394132715, 'reg_lambda': 0.012713830138914988}. Best is trial 20 with value: 0.5504056068686063.


[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.039249 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 25872
[LightGBM] [Info] Number of data points in the train set: 58507, number of used features: 141


[I 2024-04-27 22:44:11,752] Trial 22 finished with value: 0.5482295924262232 and parameters: {'num_leaves': 55, 'max_depth': 9, 'learning_rate': 0.05134728909850306, 'num_boost_round': 157, 'min_child_samples': 39, 'reg_alpha': 0.3333752378841922, 'reg_lambda': 0.20067921760966234}. Best is trial 20 with value: 0.5504056068686063.


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.153351 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25872
[LightGBM] [Info] Number of data points in the train set: 58507, number of used features: 141


[I 2024-04-27 22:44:28,252] Trial 23 finished with value: 0.5412089621946424 and parameters: {'num_leaves': 37, 'max_depth': 9, 'learning_rate': 0.15386057756025817, 'num_boost_round': 148, 'min_child_samples': 39, 'reg_alpha': 0.3295302915826223, 'reg_lambda': 0.00676073265755775}. Best is trial 20 with value: 0.5504056068686063.


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.107510 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25872
[LightGBM] [Info] Number of data points in the train set: 58507, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further sp

[I 2024-04-27 22:45:00,720] Trial 24 finished with value: 0.5480914060927118 and parameters: {'num_leaves': 66, 'max_depth': 7, 'learning_rate': 0.058982631823707915, 'num_boost_round': 325, 'min_child_samples': 45, 'reg_alpha': 0.19546511258362453, 'reg_lambda': 0.1932224499587267}. Best is trial 20 with value: 0.5504056068686063.


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.105201 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25872
[LightGBM] [Info] Number of data points in the train set: 58507, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further sp

[I 2024-04-27 22:45:29,004] Trial 25 finished with value: 0.5436962259773467 and parameters: {'num_leaves': 56, 'max_depth': 8, 'learning_rate': 0.09406704162286272, 'num_boost_round': 255, 'min_child_samples': 36, 'reg_alpha': 0.46486918799361904, 'reg_lambda': 0.08783771441179906}. Best is trial 20 with value: 0.5504056068686063.


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.156290 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25872
[LightGBM] [Info] Number of data points in the train set: 58507, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf


[I 2024-04-27 22:46:04,508] Trial 26 finished with value: 0.5367889383435697 and parameters: {'num_leaves': 39, 'max_depth': 9, 'learning_rate': 0.14975412323584908, 'num_boost_round': 381, 'min_child_samples': 40, 'reg_alpha': 0.32203939720841246, 'reg_lambda': 0.21940140277819087}. Best is trial 20 with value: 0.5504056068686063.


[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.040443 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 25872
[LightGBM] [Info] Number of data points in the train set: 58507, number of used features: 141


[I 2024-04-27 22:46:31,978] Trial 27 finished with value: 0.543218494969491 and parameters: {'num_leaves': 27, 'max_depth': 7, 'learning_rate': 0.039675956691238135, 'num_boost_round': 296, 'min_child_samples': 32, 'reg_alpha': 0.620462360803193, 'reg_lambda': 0.003593190721719264}. Best is trial 20 with value: 0.5504056068686063.


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.101311 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25872
[LightGBM] [Info] Number of data points in the train set: 58507, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf


[I 2024-04-27 22:46:58,625] Trial 28 finished with value: 0.5516560577655624 and parameters: {'num_leaves': 49, 'max_depth': 10, 'learning_rate': 0.10523945951163613, 'num_boost_round': 245, 'min_child_samples': 46, 'reg_alpha': 0.14230649990869138, 'reg_lambda': 0.13435149240608613}. Best is trial 28 with value: 0.5516560577655624.


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.100432 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25872
[LightGBM] [Info] Number of data points in the train set: 58507, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf


[I 2024-04-27 22:47:27,923] Trial 29 finished with value: 0.5443813928805104 and parameters: {'num_leaves': 63, 'max_depth': 10, 'learning_rate': 0.10217593205146389, 'num_boost_round': 245, 'min_child_samples': 48, 'reg_alpha': 0.13832830211955716, 'reg_lambda': 0.32032458004043424}. Best is trial 28 with value: 0.5516560577655624.


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.098699 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25872
[LightGBM] [Info] Number of data points in the train set: 58507, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further sp

[I 2024-04-27 22:47:56,025] Trial 30 finished with value: 0.5356562059077742 and parameters: {'num_leaves': 49, 'max_depth': 5, 'learning_rate': 0.13195664795265893, 'num_boost_round': 371, 'min_child_samples': 44, 'reg_alpha': 0.006148985552901554, 'reg_lambda': 0.13493597733883872}. Best is trial 28 with value: 0.5516560577655624.


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.102016 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25872
[LightGBM] [Info] Number of data points in the train set: 58507, number of used features: 141


[I 2024-04-27 22:48:16,430] Trial 31 finished with value: 0.5397404542121371 and parameters: {'num_leaves': 59, 'max_depth': 9, 'learning_rate': 0.023906161943959482, 'num_boost_round': 158, 'min_child_samples': 40, 'reg_alpha': 0.386299823594448, 'reg_lambda': 0.05425314304340681}. Best is trial 28 with value: 0.5516560577655624.


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.102326 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25872
[LightGBM] [Info] Number of data points in the train set: 58507, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf


[I 2024-04-27 22:48:43,019] Trial 32 finished with value: 0.5439353729335136 and parameters: {'num_leaves': 55, 'max_depth': 9, 'learning_rate': 0.06618478872278895, 'num_boost_round': 230, 'min_child_samples': 36, 'reg_alpha': 0.25209154678485407, 'reg_lambda': 0.21692757212016667}. Best is trial 28 with value: 0.5516560577655624.


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.157753 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25872
[LightGBM] [Info] Number of data points in the train set: 58507, number of used features: 141


[I 2024-04-27 22:49:10,363] Trial 33 finished with value: 0.5462267534553428 and parameters: {'num_leaves': 44, 'max_depth': 10, 'learning_rate': 0.09754005942486602, 'num_boost_round': 263, 'min_child_samples': 46, 'reg_alpha': 0.48670619717615393, 'reg_lambda': 0.14571012007609652}. Best is trial 28 with value: 0.5516560577655624.


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.125745 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25872
[LightGBM] [Info] Number of data points in the train set: 58507, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further sp

[I 2024-04-27 22:49:26,273] Trial 34 finished with value: 0.5353273153651652 and parameters: {'num_leaves': 69, 'max_depth': 9, 'learning_rate': 0.18349228514186222, 'num_boost_round': 114, 'min_child_samples': 43, 'reg_alpha': 0.17361415420289328, 'reg_lambda': 0.2757760789815612}. Best is trial 28 with value: 0.5516560577655624.


[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.044629 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 25872
[LightGBM] [Info] Number of data points in the train set: 58507, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf


[I 2024-04-27 22:49:57,960] Trial 35 finished with value: 0.5453638129301981 and parameters: {'num_leaves': 50, 'max_depth': 8, 'learning_rate': 0.1331655113153167, 'num_boost_round': 307, 'min_child_samples': 33, 'reg_alpha': 0.29459319574504106, 'reg_lambda': 0.4537525403059324}. Best is trial 28 with value: 0.5516560577655624.


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.103937 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25872
[LightGBM] [Info] Number of data points in the train set: 58507, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf


[I 2024-04-27 22:50:38,479] Trial 36 finished with value: 0.5516003533366073 and parameters: {'num_leaves': 59, 'max_depth': 9, 'learning_rate': 0.0648659065173446, 'num_boost_round': 356, 'min_child_samples': 39, 'reg_alpha': 0.712866435250945, 'reg_lambda': 0.061241110455963504}. Best is trial 28 with value: 0.5516560577655624.


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.097310 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25872
[LightGBM] [Info] Number of data points in the train set: 58507, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf


[I 2024-04-27 22:51:23,580] Trial 37 finished with value: 0.5428163243296995 and parameters: {'num_leaves': 75, 'max_depth': 10, 'learning_rate': 0.11415850762366114, 'num_boost_round': 358, 'min_child_samples': 47, 'reg_alpha': 0.7034900489036989, 'reg_lambda': 0.05773488575676766}. Best is trial 28 with value: 0.5516560577655624.


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.117668 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25872
[LightGBM] [Info] Number of data points in the train set: 58507, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further sp

[I 2024-04-27 22:51:46,883] Trial 38 finished with value: 0.5233066439806754 and parameters: {'num_leaves': 32, 'max_depth': 3, 'learning_rate': 0.2085791654859729, 'num_boost_round': 394, 'min_child_samples': 25, 'reg_alpha': 0.7687030562875086, 'reg_lambda': 0.16021382438711676}. Best is trial 28 with value: 0.5516560577655624.


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.107995 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25872
[LightGBM] [Info] Number of data points in the train set: 58507, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf


[I 2024-04-27 22:52:39,721] Trial 39 finished with value: 0.5494443834079211 and parameters: {'num_leaves': 86, 'max_depth': 9, 'learning_rate': 0.0713238868210307, 'num_boost_round': 414, 'min_child_samples': 30, 'reg_alpha': 0.700010567159326, 'reg_lambda': 0.04992876971598706}. Best is trial 28 with value: 0.5516560577655624.


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.101214 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25872
[LightGBM] [Info] Number of data points in the train set: 58507, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf


[I 2024-04-27 22:53:38,401] Trial 40 finished with value: 0.5482266543426612 and parameters: {'num_leaves': 88, 'max_depth': 10, 'learning_rate': 0.07134260354381833, 'num_boost_round': 428, 'min_child_samples': 31, 'reg_alpha': 0.8624616127879413, 'reg_lambda': 0.10502632105625942}. Best is trial 28 with value: 0.5516560577655624.


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.116520 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25872
[LightGBM] [Info] Number of data points in the train set: 58507, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further sp

[I 2024-04-27 22:54:30,782] Trial 41 finished with value: 0.5513438957693736 and parameters: {'num_leaves': 86, 'max_depth': 9, 'learning_rate': 0.09231838633605226, 'num_boost_round': 417, 'min_child_samples': 35, 'reg_alpha': 0.7296585270036898, 'reg_lambda': 0.05374687332524539}. Best is trial 28 with value: 0.5516560577655624.


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.195714 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25872
[LightGBM] [Info] Number of data points in the train set: 58507, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further sp

[I 2024-04-27 22:55:34,685] Trial 42 finished with value: 0.5448116605427326 and parameters: {'num_leaves': 86, 'max_depth': 9, 'learning_rate': 0.09154211129244068, 'num_boost_round': 500, 'min_child_samples': 30, 'reg_alpha': 0.7588981081289815, 'reg_lambda': 0.05394293064455259}. Best is trial 28 with value: 0.5516560577655624.


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.116448 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25872
[LightGBM] [Info] Number of data points in the train set: 58507, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf


[I 2024-04-27 22:56:31,975] Trial 43 finished with value: 0.5381121332177177 and parameters: {'num_leaves': 84, 'max_depth': 10, 'learning_rate': 0.16843281345445424, 'num_boost_round': 439, 'min_child_samples': 27, 'reg_alpha': 0.6963811404746633, 'reg_lambda': 0.11687947515708709}. Best is trial 28 with value: 0.5516560577655624.


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.115562 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25872
[LightGBM] [Info] Number of data points in the train set: 58507, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf


[I 2024-04-27 22:57:20,009] Trial 44 finished with value: 0.5502444804306914 and parameters: {'num_leaves': 72, 'max_depth': 9, 'learning_rate': 0.10657035113743445, 'num_boost_round': 406, 'min_child_samples': 42, 'reg_alpha': 0.9051295165439193, 'reg_lambda': 0.16992747931689098}. Best is trial 28 with value: 0.5516560577655624.


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.174232 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25872
[LightGBM] [Info] Number of data points in the train set: 58507, number of used features: 141


[I 2024-04-27 22:58:15,841] Trial 45 finished with value: 0.5449524103978599 and parameters: {'num_leaves': 72, 'max_depth': 10, 'learning_rate': 0.10417334043738125, 'num_boost_round': 470, 'min_child_samples': 41, 'reg_alpha': 0.9988194352478447, 'reg_lambda': 0.40563766904725745}. Best is trial 28 with value: 0.5516560577655624.


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.115436 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25872
[LightGBM] [Info] Number of data points in the train set: 58507, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further sp

[I 2024-04-27 22:59:02,681] Trial 46 finished with value: 0.5491644345254838 and parameters: {'num_leaves': 79, 'max_depth': 9, 'learning_rate': 0.14118841801883336, 'num_boost_round': 393, 'min_child_samples': 49, 'reg_alpha': 0.8775780918282016, 'reg_lambda': 0.2610409924381836}. Best is trial 28 with value: 0.5516560577655624.


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.180658 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25872
[LightGBM] [Info] Number of data points in the train set: 58507, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf


[I 2024-04-27 22:59:48,766] Trial 47 finished with value: 0.5504494240515068 and parameters: {'num_leaves': 91, 'max_depth': 10, 'learning_rate': 0.16756495455413667, 'num_boost_round': 344, 'min_child_samples': 38, 'reg_alpha': 0.7888350092652494, 'reg_lambda': 0.17245791715393474}. Best is trial 28 with value: 0.5516560577655624.


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.121049 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25872
[LightGBM] [Info] Number of data points in the train set: 58507, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf


[I 2024-04-27 23:00:33,455] Trial 48 finished with value: 0.5338605109093181 and parameters: {'num_leaves': 94, 'max_depth': 10, 'learning_rate': 0.21259970794275138, 'num_boost_round': 349, 'min_child_samples': 34, 'reg_alpha': 0.7974543020528618, 'reg_lambda': 0.2392664932624018}. Best is trial 28 with value: 0.5516560577655624.


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.168675 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25872
[LightGBM] [Info] Number of data points in the train set: 58507, number of used features: 141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf


[I 2024-04-27 23:01:17,268] Trial 49 finished with value: 0.5374458778404759 and parameters: {'num_leaves': 94, 'max_depth': 10, 'learning_rate': 0.17144073535928478, 'num_boost_round': 314, 'min_child_samples': 37, 'reg_alpha': 0.6565999288078915, 'reg_lambda': 0.09311450899602369}. Best is trial 28 with value: 0.5516560577655624.


In [13]:
print(f'Best NDCG@5 for LGBM on normalized data: {study_lgbm_normalized.best_value:.4f}')
print('Best hyperparameters for LGBM on normalized data:')
print(study_lgbm_normalized.best_params)

Best NDCG@5 for LGBM on normalized data: 0.5517
Best hyperparameters for LGBM on normalized data:
{'num_leaves': 49, 'max_depth': 10, 'learning_rate': 0.10523945951163613, 'num_boost_round': 245, 'min_child_samples': 46, 'reg_alpha': 0.14230649990869138, 'reg_lambda': 0.13435149240608613}


Best NDCG@5 for LGBM on normalized data: 0.5517
Best hyperparameters for LGBM on normalized data:
{'num_leaves': 49, 'max_depth': 10, 'learning_rate': 0.10523945951163613, 'num_boost_round': 245, 'min_child_samples': 46, 'reg_alpha': 0.14230649990869138, 'reg_lambda': 0.13435149240608613}

In [14]:
def objective_xgb_normalized(trial):
    params = {
        'objective': 'rank:ndcg',
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3),
        'max_depth': trial.suggest_int('max_depth', 3, 10),
        'n_estimators': trial.suggest_int('n_estimators', 50, 500),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'gamma': trial.suggest_float('gamma', 0.0, 1.0),
        'subsample': trial.suggest_float('subsample', 0.5, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 1.0),
        'reg_alpha': trial.suggest_float('reg_alpha', 0.0, 1.0),
        'reg_lambda': trial.suggest_float('reg_lambda', 0.0, 1.0)
    }

    model = XGBRanker(**params)
    model.fit(X_train_normalized, y_train_normalized, group=X_train_normalized.groupby('query_id').size().values)
    y_pred = model.predict(X_test_normalized)
    query_ids = X_test_normalized['query_id'].values
    ndcg_5 = ndcg_at_k(y_test_normalized.values, y_pred, query_ids, k=5)
    return ndcg_5

In [16]:
study_xgb_normalized = optuna.create_study(direction='maximize')
study_xgb_normalized.optimize(objective_xgb_normalized, n_trials=50)

[I 2024-04-28 11:38:25,585] A new study created in memory with name: no-name-9360fce8-f79f-433a-a0aa-aa1f65ec2c73
[I 2024-04-28 11:40:47,194] Trial 0 finished with value: 0.5291498542358632 and parameters: {'learning_rate': 0.2416446345597921, 'max_depth': 6, 'n_estimators': 443, 'min_child_weight': 5, 'gamma': 0.08543194287951605, 'subsample': 0.7170540793713815, 'colsample_bytree': 0.8338159367745881, 'reg_alpha': 0.32619438634609565, 'reg_lambda': 0.7233550795809859}. Best is trial 0 with value: 0.5291498542358632.
[I 2024-04-28 11:42:17,823] Trial 1 finished with value: 0.5242759834510562 and parameters: {'learning_rate': 0.17815058696489794, 'max_depth': 6, 'n_estimators': 266, 'min_child_weight': 2, 'gamma': 0.196967866527347, 'subsample': 0.8627047382567901, 'colsample_bytree': 0.9767673050516534, 'reg_alpha': 0.5903722221875336, 'reg_lambda': 0.46151380119149377}. Best is trial 0 with value: 0.5291498542358632.
[I 2024-04-28 11:44:26,674] Trial 2 finished with value: 0.50488235

In [17]:
print(f'Best NDCG@5 for XGB on normalized data: {study_xgb_normalized.best_value:.4f}')
print('Best hyperparameters for XGB on normalized data:')
print(study_xgb_normalized.best_params)

Best NDCG@5 for XGB on normalized data: 0.5416
Best hyperparameters for XGB on normalized data:
{'learning_rate': 0.13541471418335874, 'max_depth': 10, 'n_estimators': 475, 'min_child_weight': 8, 'gamma': 0.055597247241479325, 'subsample': 0.7993063842562708, 'colsample_bytree': 0.8843911166501889, 'reg_alpha': 0.6321697450018331, 'reg_lambda': 0.4244566664938659}


Best NDCG@5 for XGB on normalized data: 0.5416
Best hyperparameters for XGB on normalized data:
{'learning_rate': 0.13541471418335874, 'max_depth': 10, 'n_estimators': 475, 'min_child_weight': 8, 'gamma': 0.055597247241479325, 'subsample': 0.7993063842562708, 'colsample_bytree': 0.8843911166501889, 'reg_alpha': 0.6321697450018331, 'reg_lambda': 0.4244566664938659}